export const CREATE_MAP = "CREATE_MAP";
export const UPDATE_USER = "UPDATE_USER";

export const ADD_CHARACTER = "ADD_CHARACTER";
export const UPDATE_CHARACTER_INFO = "UPDATE_CHARACTER_INFO";
export const DELETE_CHARACTER = "DELETE_CHARACTER";
export const MOVE_CHARACTER = "MOVE_CHARACTER";
export const SET_CHARACTER = "SET_CHARACTER";

export const END_TURN = "END_TURN";
export const SET_TURN = "SET_TURN";

export const TOGGLE_EDIT_MODE = "TOGGLE_EDIT_MODE";
export const TOGGLE_PRIVATE_MAP = "TOGGLE_PRIVATE_MAP";

export const SELECT_OBJECT = "SELECT_OBJECT";
export const SET_OBJECT = "SET_OBJECT";

export const UPDATE_MAP_NAME = "UPDATE_MAP_NAME";
export const SAVE_MAP = "SAVE_MAP";
export const USE_SELECTED_MAP = "USE_SELECTED_MAP";

export const NO_ACTION = "NO_ACTION";
