export const SET_OBJECT = "SET_OBJECT";
export const SELECT_OBJECT = "SELECT_OBJECT";
export const MOVE_CHARACTER = "MOVE_CHARACTER";
export const MOVE_BOARD = "MOVE_BOARD";
export const TOGGLE_EDIT_MODE = "TOGGLE_EDIT_MODE";
