export const CREATE_MAP = "CREATE_MAP";
export const ADD_CHARACTER = "ADD_CHARACTER";
export const SET_CHARACTER = "SET_CHARACTER";
export const MOVE_CHARACTER = "MOVE_CHARACTER";
export const UPDATE_CHARACTER_INFO = "UPDATE_CHARACTER_INFO";
export const DELETE_CHARACTER = "DELETE_CHARACTER";
export const TOGGLE_EDIT_MODE = "TOGGLE_EDIT_MODE";
export const SELECT_OBJECT = "SELECT_OBJECT";
export const SET_OBJECT = "SET_OBJECT";
export const END_TURN = "END_TURN";
export const SET_TURN = "SET_TURN";
export const NO_ACTION = "NO_ACTION";

export const MOVE_BOARD = "MOVE_BOARD";
